sonar.projectKey=esi_edl_compData_product_consumer
sonar.javascript.lcov.reportPaths=compData_product_consumer/coverage/lcov.info
sonar.sources=compData_product_consumer/src
sonar.coverage.exclusions=**/config.ts,**/test/*
sonar.cpd.exclusions=**/test/*